"""Case 3 (Mirror Game) reproduction: config and entry points."""
from __future__ import annotations

from . import config
from .pca import (
    build_aligned_dataset,
    plot_principal_movements,
    plot_variance,
    run_pca_diagnostic,
)
from .reproduce import (
    KINEMATIC_FEATURES,
    load_and_resample,
    default_conditions_csv,
    load_condition_map,
    load_leader_map,
    delay_embed,
    kinematic_summary,
    md_cross_rqa_row,
    md_cross_rqa_fixed_row,
    cross_params_fixed,
    run_crqa_radius_sweep,
    run_surrogate_analysis,
    run_auto_rqa_analysis,
    run_embedding_estimates,
    run_embedding_sweep,
    md_radius_sweep,
    run_md_radius_sweep,
    movement_long,
    movement_summary,
    parse_file,
    plot_case3_figure,
    plot_md_figure,
    process_dyad,
    run_reproduction,
)

__all__ = [
    "config",
    "KINEMATIC_FEATURES",
    "load_and_resample",
    "default_conditions_csv",
    "load_condition_map",
    "load_leader_map",
    "delay_embed",
    "kinematic_summary",
    "md_cross_rqa_row",
    "md_cross_rqa_fixed_row",
    "cross_params_fixed",
    "run_crqa_radius_sweep",
    "run_surrogate_analysis",
    "run_auto_rqa_analysis",
    "run_embedding_estimates",
    "run_embedding_sweep",
    "md_radius_sweep",
    "run_md_radius_sweep",
    "movement_long",
    "movement_summary",
    "parse_file",
    "process_dyad",
    "run_reproduction",
    "plot_case3_figure",
    "plot_md_figure",
    "build_aligned_dataset",
    "run_pca_diagnostic",
    "plot_variance",
    "plot_principal_movements",
]
